# Generated by Django 3.0.5 on 2020-08-16 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_question_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'UserInfo'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='phonerror', message='Input 10 digit phone number', regex='^.{10}$')]),
        ),
    ]
