# Generated by Django 3.0.5 on 2020-08-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_auto_20200816_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(blank=True, to='Task.Choices'),
        ),
    ]
