# Generated by Django 3.0.5 on 2020-08-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_auto_20200817_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='require',
            new_name='required',
        ),
    ]
