# Generated by Django 3.0.5 on 2020-08-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0007_auto_20200817_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('input_box', 'input_box'), ('select_box', 'select_box')], default='input', max_length=50),
        ),
    ]
