# Generated by Django 3.0.5 on 2020-08-16 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_auto_20200817_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
