# Generated by Django 3.0.5 on 2020-08-16 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0009_auto_20200817_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
